### ISSUE TITLE
Cells in mailer views

### ISSUE THREAD

**Issue by Startouf** [trailblazer/cells-rails#14]
Hey, I cannot figure out how to add cells in my mailers.

The `cell`method is not recognized in my mailers, and when I call the cell by its name `MyCell.()` I get a constant unknown error.

What's the proper way to include cells (ideally the `cell` helper) in Rails mailers ?

**Comment by Startouf** [comment]
So you're suggesting I should make a PR with similar code for ActionMailer ?

And otherwise sorry, I was calling `MyCell.new(@myObject).method` instead of using the call syntax `MyCell.().()` ....

**Comment by apotonick** [comment]
Uhm, yeah, why not, I actually never thought of the ActionMailer patch. Is that really necessary, though??

**Comment by Startouf** [comment]
Well just now I was telling someone about the awesomeness of cells, and that we could also use it for Mailer views, then we got stuck for 30 minutes because `cell(xx)` wasn't working and we tried different combinations of `helper Cell:xxx` into ApplicationMailer which weren't working

**Comment by apotonick** [comment]
Yeah but then you run into the next problem, what will be the parent controller in a mailer, and so on...

The `Cell.()` works everywhere since it's pure Ruby.

**Comment by apotonick** [comment]
But I agree, Cells are awesome! :laughing:

**Comment by Startouf** [comment]
Hey I still have some problems in cells in mailers with URL helpers.
cells-rails include a default `parent_controller` in the context that is used to resolve `link_to` links. When calling the raw Cell with `MyCell.call(@myObject).call(:view_name)` this property is not passed and calling link_to in mailer views cause this problem

```
cells-rails-0.0.6/lib/cell/rails.rb:58:in `parent_controller'
actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:228:in `call'
actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:177:in `call'
actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:295:in `block (2 levels) in define_url_helper'
app/cells/mailer/appointment/line_that_calls_link_to
```

My current solution is not to call directly `link_to` but only use directly the url_helper in the href attribute `<a href="<%= my_resource_url(model) %>`

I have added an `include Rails.application.routes.url_helpers` in my cell for this to work.

**Comment by Startouf** [comment]
This problem is still causing me headaches whenever I call new url_helpers in my mailer cell view and those are not delegated using the trick mentioned above. The stack trace also remains enigmatic so it took me some time to remember I had to re-delegate the helpers in my cell.rb file. 
I've noticed there was a TRB repository with cells made especially for mailers, but that's not something I can use right now and it feels like it was quite abandonned... ?
Also I just watched the Ruby is Dead talk and I can't help but wink @apotonick https://youtu.be/x0JlOxdXA_g?t=23m28s
