### ISSUE TITLE
uninitialized constant Cell::Collection

### ISSUE THREAD

**Issue by Startouf** [trailblazer/cells-rails#3]
Trace up to config.ru

```
C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cells-rails-0.0.4/lib/cell/railtie.rb:39:in `block in <class:Railtie>': uninitialized constant Cell::Collection (NameError)
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta4/lib/rails/initializable.rb:30:in `instance_exec'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta4/lib/rails/initializable.rb:30:in `run'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta4/lib/rails/initializable.rb:55:in `block in run_initializers'
        from C:/Dev/Ruby22-x64/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
        from C:/Dev/Ruby22-x64/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from C:/Dev/Ruby22-x64/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
        from C:/Dev/Ruby22-x64/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from C:/Dev/Ruby22-x64/lib/ruby/2.2.0/tsort.rb:345:in `each'
        from C:/Dev/Ruby22-x64/lib/ruby/2.2.0/tsort.rb:345:in `call'
        from C:/Dev/Ruby22-x64/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
        from C:/Dev/Ruby22-x64/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
        from C:/Dev/Ruby22-x64/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta4/lib/rails/initializable.rb:54:in `run_initializers'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta4/lib/rails/application.rb:352:in `initialize!'
        from C:/Dev/myProject/config/environment.rb:12:in `<top (required)>'
        from C:/Dev/myProject/config.ru:3:in `block in <main>'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `instance_eval'
        from C:/Dev/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `initialize'
        from C:/Dev/myProject/config.ru:in `new'
```

**Comment by Na0na0** [comment]
Hi! What version of cells are you using in your app?
If I recall, Cell::Collection was only implemented in cells 4.1, which is required by cells-rails anyway

I add the same problem, in the meantime, before a stable 4.1 release, make sure that bundle installs the right version of cell in your Gemfile
`gem 'cells', '~> 4.1.0.rc1'`

**Comment by Startouf** [comment]
I'm using Cells 4.0.5, will try to upgrade

**Comment by apotonick** [comment]
Yepp, please upgrade to 4.1.0.rc1.
