### ISSUE TITLE
Cells-Rails 0.1.4 does not work with Rails 7.0.3 

### ISSUE THREAD

**Issue by alecslupu** [trailblazer/cells-rails#66]
Currently, while trying to use 0.1.4 version of cells-rails to perform a rails 7.0 upgrade, i get the following error : 

```
  5) Decidim::Forms::QuestionReadonlyCell when using a separator doesn't render anything
     Failure/Error:
           def initialize(env, session, controller_class)
             super(env)
       
             self.session = session
             self.session_options = TestSession::DEFAULT_OPTIONS.dup
             @controller_class = controller_class
             @custom_param_parsers = {
               xml: lambda { |raw_post| Hash.from_xml(raw_post)["hash"] }
             }
           end
     
     ArgumentError:
       wrong number of arguments (given 0, expected 3)
     # /bundle_cache/ruby/3.0.0/gems/actionpack-7.0.3/lib/action_controller/test_case.rb:57:in `initialize'
     # /bundle_cache/ruby/3.0.0/gems/cells-rails-0.1.4/lib/cell/rails/testing.rb:26:in `new'
     # /bundle_cache/ruby/3.0.0/gems/cells-rails-0.1.4/lib/cell/rails/testing.rb:26:in `action_controller_test_request'
     # /bundle_cache/ruby/3.0.0/gems/cells-rails-0.1.4/lib/cell/rails/testing.rb:13:in `block in controller_for'
     # <internal:kernel>:90:in `tap'
     # /bundle_cache/ruby/3.0.0/gems/cells-rails-0.1.4/lib/cell/rails/testing.rb:12:in `controller_for'
     # /bundle_cache/ruby/3.0.0/gems/rspec-cells-0.3.7/lib/rspec/cells/example_group.rb:60:in `block (2 levels) in <module:ExampleGroup>'
     # /code/decidim/decidim-dev/lib/decidim/dev/test/rspec_support/warden.rb:25:in `block (2 levels) in <main>'
     # /bundle_cache/ruby/3.0.0/gems/rspec-cells-0.3.7/lib/rspec/cells/example_group.rb:50:in `block (2 levels) in <module:ExampleGroup>'
     # /bundle_cache/ruby/3.0.0/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <main>'

```

Opening the code in the repo, i can see 
https://github.com/trailblazer/cells-rails/blob/73c57092c058852f4dc98ddcfb1f2004c94052fc/lib/cell/rails/testing.rb#L5
But when opening the ruby gems version, i get https://github.com/trailblazer/cells-rails/blob/901d2d663ce075bf89c439019dbf2e4a9801d718/lib/cell/rails/testing.rb#L5

Changing the line from the gem with the one in repository, fixes the issue. 

Maybe a new 0.1.5 version should be released?

**Comment by richardboehme** [comment]
I released a new version 0.1.5 :rocket:
